---
abstract: 'MIME::BaseX - Encoding and decoding of base16, base32, base64 and base64url'
author:
  - 'Lucas Tiago de Moraes'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.36, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MIME-BaseX
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '5.57'
  MIME::Base64: '3.11'
  XSLoader: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/lucas1/MIME-BaseX/issues
  homepage: https://github.com/lucas1/MIME-BaseX
  repository: https://github.com/lucas1/MIME-BaseX
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
